### ISSUE TITLE
blank label

### ISSUE THREAD

**Issue by Cifer-Y** [DavidLGoldberg/jumpy#69]
![jumpy_issue](https://cloud.githubusercontent.com/assets/4470516/8615309/2aa19134-2724-11e5-98dc-50781f53162c.png) 
atom 1.0.2

**Comment by DavidLGoldberg** [comment]
Works for me fine on my Atom 1.0.2 Can you check what's in your custom style sheet?

Can you try killing and restarting Atom, also make sure you're on the latest jumpy.

Is this all of the time, or are there steps to reproduce it?

**Comment by Cifer-Y** [comment]
I konw what's happened. The atom material UI theme is the reason. Seems jumpy didn't work well with the Atom Material UI Theme.

**Comment by DavidLGoldberg** [comment]
Thanks, I'll take a look when I get a chance.

**Comment by t-hiroyoshi** [comment]
+1

**Comment by livelazily** [comment]
Add this to `~/.atom/style.less` work for me
```less
@import "ui-variables";
.theme-atom-material-ui {
    atom-text-editor::shadow .jumpy {
        &.label {
            opacity: 0.8;
            color: @text-color-highlight;
            background-color: @background-color-selected;
        }
    }
}
```

This maybe work for #74 also
