### ISSUE TITLE
Transparecy

### ISSUE THREAD

**Issue by Spectator6** [DavidLGoldberg/jumpy#88]
Great work with jumpy, it's very useful!

Any chance of including a transparency option for the overlay?

**Comment by DavidLGoldberg** [comment]
I had this at launch I think (or a little later).

Lots of us thought it was noisey / ugly.  I'll leave this ticket open, to help you out with it..

But going to leave it to you.. The readme has the basics.  Give it a shot, ask some questions if you have trouble.  Be sure to post it if you get it!

**Comment by DavidLGoldberg** [comment]
The following comes from the README.md which has been updated recently to remove '/deep/' (you don't need it).
```css
atom-text-editor {
    .jumpy-label {
        &.high-contrast {
            opacity: .8;
        }
    }
}
```
